# Generated by Django 4.1 on 2024-08-03 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sublets.models


class Migration(migrations.Migration):

    dependencies = [
        ("sublets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("address_line_1", models.CharField(max_length=35)),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ("Boston Area", "Boston Area"),
                            ("New York City", "New York City"),
                            ("Philadelphia", "Philadelphia"),
                        ],
                        max_length=28,
                    ),
                ),
                ("state", models.CharField(max_length=14)),
                ("rent", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "listing_type",
                    models.CharField(
                        choices=[
                            ("room_in_apartment", "Rent a room in a shared apartment"),
                            (
                                "entire_apartment",
                                "Rent an entire apartment to yourself",
                            ),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="sublets.listing",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_inbox",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_outbox",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ListingPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(upload_to=sublets.models.listing_photo_path),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="sublets.listing",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="saved_listings",
            field=models.ManyToManyField(
                related_name="users_who_saved", to="sublets.listing"
            ),
        ),
    ]
