# Generated by Django 5.0.7 on 2024-08-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sublets", "0002_alter_profilepicture_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(max_length=35, null=True),
        ),
    ]
