# Generated by Django 5.0.7 on 2024-08-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sublets", "0003_listing_zip_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="bathroom_count",
            field=models.CharField(
                choices=[
                    ("1", "One"),
                    ("1.5", "One and a half"),
                    ("2", "Two"),
                    ("2.5", "Two and a half"),
                    ("3", "Three"),
                    ("3.5", "Three and a half"),
                    ("4", "Four"),
                ],
                default=0,
                max_length=14,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="listing",
            name="bedroom_count",
            field=models.IntegerField(default="1"),
            preserve_default=False,
        ),
    ]
